dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  firebase_storage: ^11.6.10
  provider: ^6.1.1
  image_picker: ^1.0.7
  video_player: ^2.8.2
  cloudinary: ^1.2.0
  cloudinary_url_gen: ^1.5.0
  cloudinary_flutter: ^1.0.0

  # Web-specific dependencies
  video_player_web: ^2.1.3
  image_picker_for_web: ^3.0.2
  firebase_auth_web: ^5.9.9
  cloud_firestore_web: ^3.10.9
  firebase_storage_web: ^3.6.11
  firebase_core_web: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 